- name: Restart caddy
  ansible.builtin.service:
    name: caddy
    state: restarted

- name: Restart edge-node caddy
  ansible.builtin.service:
    name: caddy
    state: restarted
  delegate_to: edge-node

- name: Restart tailscaled
  ansible.builtin.service:
    name: tailscaled
    state: restarted

- name: Restart edge-node haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
  delegate_to: edge-node

- name: Restart valkey
  ansible.builtin.service:
    name: valkey
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
