---
# Main tasks for GitHub runner role

- name: Validate required variables
  ansible.builtin.assert:
    that:
      - github_runner_registration_token | length > 0
      - (github_runner_org | length > 0) or (github_runner_repo | length > 0)
    fail_msg: "github_runner_registration_token and either github_runner_org or github_runner_repo must be set"

- name: Download github cli gpg key
  ansible.builtin.get_url:
    url: "https://cli.github.com/packages/githubcli-archive-keyring.gpg"
    dest: "/etc/apt/trusted.gpg.d/githubcli-archive-keyring.gpg"
    mode: "0644"

- name: Add github cli repository
  ansible.builtin.apt_repository:
    repo: "deb https://cli.github.com/packages stable main"
    state: present
    filename: "github-cli"
    update_cache: true

- name: Install additional packages if specified
  ansible.builtin.apt:
    name: "{{ github_runner_packages_to_install }}"
    state: present
    cache_valid_time: 3600
  when: github_runner_packages_to_install | length > 0

- name: Create Runner Group
  ansible.builtin.group:
    name: "{{ github_runner_group }}"
    state: present
    system: true
    gid: 1500

- name: Create Runner User
  ansible.builtin.user:
    name: "{{ github_runner_user }}"
    state: present
    groups: "{{ github_runner_group }},sudo"
    home: "/home/{{ github_runner_user }}"
    shell: "/bin/bash"
    createhome: true
    uid: 1500

- name: Create runner directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ github_runner_user }}"
    group: "{{ github_runner_group }}"
    mode: "0755"
  loop:
    - "{{ github_runner_dir }}"
    - "{{ github_runner_work_dir }}"
    - "{{ github_runner_base_dir }}/.config"

- name: Check if runner is already installed
  ansible.builtin.stat:
    path: "{{ github_runner_dir }}/bin/Runner.Listener"
  register: runner_installed

- name: Download GitHub Actions runner
  ansible.builtin.unarchive:
    src: "{{ github_runner_download_url }}"
    dest: "{{ github_runner_dir }}"
    owner: "{{ github_runner_user }}"
    group: "{{ github_runner_group }}"
    remote_src: true
    creates: "{{ github_runner_dir }}/bin/Runner.Listener"
  when: not runner_installed.stat.exists

- name: Check if runner is already configured
  ansible.builtin.stat:
    path: "{{ github_runner_dir }}/.runner"
  register: runner_configured

- name: Configure runner for organization
  ansible.builtin.shell:
    cmd: |
      ./config.sh \
        --url https://github.com/{{ github_runner_org }} \
        --token {{ github_runner_registration_token }} \
        --name {{ github_runner_name }} \
        --labels {{ github_runner_labels }} \
        --work {{ github_runner_work_dir }} \
        --unattended \
        --replace
    chdir: "{{ github_runner_dir }}"
  become: true
  become_user: "{{ github_runner_user }}"
  when:
    - not runner_configured.stat.exists
    - github_runner_org | length > 0
    - github_runner_repo | length == 0

- name: Configure runner for repository
  ansible.builtin.shell:
    cmd: |
      ./config.sh \
        --url https://github.com/{{ github_runner_repo }} \
        --token {{ github_runner_registration_token }} \
        --name {{ github_runner_name }} \
        --labels {{ github_runner_labels }} \
        --work {{ github_runner_work_dir }} \
        --unattended \
        --replace
    chdir: "{{ github_runner_dir }}"
  become: true
  become_user: "{{ github_runner_user }}"
  when:
    - not runner_configured.stat.exists
    - github_runner_repo | length > 0

- name: Install runner service
  ansible.builtin.command:
    cmd: >
      ./svc.sh install {{ github_runner_user }}
    chdir: "{{ github_runner_dir }}"
  become: true
  args:
    creates: "/etc/systemd/system/{{ github_runner_service_name }}.service"

- name: Update systemd service file
  ansible.builtin.template:
    src: github-runner.service.j2
    dest: "/etc/systemd/system/{{ github_runner_service_name }}.service"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd daemon
    - Restart github runner

- name: Start and enable runner service
  ansible.builtin.systemd:
    name: "{{ github_runner_service_name }}"
    state: started
    enabled: true
    daemon_reload: true
