- name: Install Ares Servers
  hosts: aresmush_servers
  become: true
  tags:
    - ares-servers
  roles:
    - role: artis3n.tailscale.machine
      vars:
        tailscale_authkey: "{{ lookup('community.general.onepassword', 'tailscale-oauth ares-game-host', field='password', vault='fzymgc-house') }}"
        tailscale_args: "--ssh --accept-dns --reset"
        tailscale_oauth_preauthorized: true
        tailscale_oauth_ephemeral: false
        tailscale_tags: [ares-game-node]
      tags: tailscale
    - role: ares
      tags: ares
