---
- name: Bootstrap GitHub Actions Runners
  hosts: github_runners
  gather_facts: false
  become: false
  vars:
    ansible_connection: community.general.incus
    ansible_incus_remote: nas
    ansible_become: false
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Wait for cloud-init to complete
      ansible.builtin.command:
        cmd: cloud-init status --wait
      changed_when: false
      failed_when: "'done' not in cloud_init_wait.stdout"
      register: cloud_init_wait
      tags:
        - always

- name: Configure GitHub Actions Runners
  hosts: github_runners
  gather_facts: true
  become: true

  roles:
    - role: common
      tags:
        - common
    - role: geerlingguy.docker
      vars:
        docker_users: [fzymgc]
        docker_install_compose_plugin: true
        docker_compose_package: docker-compose-plugin
        docker_compose_package_state: present
      tags: docker
    - role: github-runner
      tags:
        - github-runner
