network:
  renderer: networkd
  version: 2
  ethernets:
    eth0:
      dhcp4: true
      dhcp6: true
      ipv6-privacy: false
      accept-ra: true
    eth1:
      dhcp4: true
      dhcp6: true
      ipv6-privacy: false
      accept-ra: true
