---
ungrouped:
  hosts:
    edge-node:
      ansible_user: root
      ansible_become: false
      ansible_host: edge-node

incus:
  vars:
    ansible_connection: community.general.incus
    ansible_incus_remote: nas
    ansible_become: false
    ansible_user: root
  hosts:
    nas-support:
      ansible_hostname: nas-support
      ansible_host: "nas-support.{{ primary_domain }}"
      ansible_fqdn: "nas-support.{{ primary_domain }}"
      reboot_offset: 15m
      install_time: 01:45
      reboot_time: 02:15
      network_eth0:
        type: dhcp
        interface_name: eth0
      network_eth1:
        type: dhcp
        interface_name: eth1
        use_dhcp_routes: false
        dns_address: "{{ ansible_eth1.ipv4.address }}"
        dns_domain: incus
    nas-container-apps:
      ansible_hostname: nas-container-apps
      ansible_host: "nas-container-apps.{{ primary_domain }}"
      ansible_fqdn: "nas-container-apps.{{ primary_domain }}"
      reboot_offset: 15m
      install_time: 02:00
      reboot_time: 02:30
      network_eth0:
        type: static
        interface_name: eth0
        ipv4_address: 192.168.20.202/22
        ipv6_address: 2600:4040:27d2:4802::202/64
        gateway: "{{ primary_dns_server }}"
        dns: "{{ primary_dns_server }}"
      network_eth1:
        type: dhcp
        interface_name: eth1
        use_dhcp_routes: false
        dns_address: "{{ ansible_eth1.ipv4.address }}"
        dns_domain: incus
    doorsportal1:
      ansible_hostname: doorsportal1
      ansible_host: "doorsportal1.{{ primary_domain }}"
      ansible_fqdn: "doorsportal1.{{ primary_domain }}"
      game_host_name: "{{ ansible_fqdn.split(\".\")[0] }}"
      game_host_domain: muxserver.net
      game_host_port: 4211
      game_db_password: "{{ lookup('onepassword', 'aresmush-db-password-doorsportal1', vault='fzymgc-house', field='password') }}"
      game_engine_api_key: "{{ lookup('onepassword', 'aresmush-engine-api-key-doorsportal1', vault='fzymgc-house', field='password') }}"
      reboot_offset: 15m
      install_time: 03:00
      reboot_time: 03:30
      network_eth0:
        type: dhcp
        interface_name: eth0
    precipice:
      ansible_hostname: precipice
      ansible_host: "precipice.{{ primary_domain }}"
      ansible_fqdn: "precipice.{{ primary_domain }}"
      game_host_name: "{{ ansible_fqdn.split(\".\")[0] }}"
      game_host_domain: muxserver.net
      game_host_port: 4201
      game_db_password: "{{ lookup('onepassword', 'aresmush-db-password-precipice', vault='fzymgc-house', field='password') }}"
      game_engine_api_key: "{{ lookup('onepassword', 'aresmush-engine-api-key-precipice', vault='fzymgc-house', field='password') }}"
      reboot_offset: 15m
      install_time: 03:45
      reboot_time: 04:15
      network_eth0:
        type: dhcp
        interface_name: eth0

aresmush_servers:
  hosts:
    doorsportal1:
    precipice:

github_runners:
  hosts:
    gh-runner:
      ansible_hostname: gh-runner
      ansible_host: "gh-runner.{{ primary_domain }}"
      ansible_fqdn: "gh-runner.{{ primary_domain }}"
      ansible_connection: ssh
      ansible_become: true
      ansible_user: fzymgc
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_pipelining: true
      network_eth0:
        type: dhcp
        interface_name: eth0
        dns_domain: "{{ primary_domain }}"
        dns_address: "{{ primary_dns_server }}"
      github_runner_name: gh-runner
      github_runner_registration_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35323734373730386532666330643566653363323730386536303964323964666535373862396638
          3465653434333864613732343839376432383530373030310a303934373238393061323963376439
          34306562303863373432633233313639616664663665643338643735316466356333663435633262
          6133636236643562610a653264616437646436653864653736303766653932633933653465323839
          35363130636137396132326530613532623062646237323735323734363632653936
