---
- name: Configure nas-syncthing-sean site
  ansible.builtin.blockinfile:
    dest: /etc/caddy/Caddyfile
    mode: "0640"
    owner: caddy
    group: caddy
    marker: "# {mark} NAS-SYNCTHING-SEAN SITE"
    insertafter: EOF
    append_newline: true
    create: true
    content: "{{ lookup('ansible.builtin.template', 'Caddyfile-site.j2', variable_start_string='%[', variable_end_string=']%', block_start_string='%[-', block_end_string='%]',
      template_vars=dict(
        site_fqdn='nas-syncthing-sean.fzymgc.house',
        site_upstream_url='http://192.168.20.200:20910',
        site_tls_cloudflare=true,
        site_upstream_tls=false,
        use_local_resolvers=true
      )) }}"
    validate: "/usr/bin/caddy validate --adapter caddyfile --config %s"
  notify:
    - Restart caddy