#SPDX-License-Identifier: MIT-0
---
# vars file for capps-komodo

stacks_base_dir: /mnt/stacks
stacks_dir_owner: apps
stacks_dir_group: apps
stacks_dir_mode: "0755"

host_data_base_dir: /mnt/data
host_data_dir_owner: apps
host_data_dir_group: apps
host_data_dir_mode: "0755"