---
- ansible.builtin.set_fact:
    cloudflare_api_token: "{{ lookup('community.general.onepassword', 'cloudflare-api-token', field='password', vault='fzymgc-house') }}"
    zerossl_key_id: "{{ lookup('community.general.onepassword', 'zerossl-eab-creds', field='username', vault='fzymgc-house') }}"
    zerossl_mac_key: "{{ lookup('community.general.onepassword', 'zerossl-eab-creds', field='password', vault='fzymgc-house') }}"
  tags:
    - caddy
    - caddy-sites

# Import all site configurations
- name: Import komodo site configuration
  ansible.builtin.import_tasks: sites/komodo.yml

- name: Import nas-storj site configuration
  ansible.builtin.import_tasks: sites/nas-storj.yml

- name: Import nas-syncthing-sean site configuration
  ansible.builtin.import_tasks: sites/nas-syncthing-sean.yml

- name: Import nas site configuration
  ansible.builtin.import_tasks: sites/nas.yml

- name: Import searxng site configuration
  ansible.builtin.import_tasks: sites/searxng.yml

- name: Import karakeep site configuration
  ansible.builtin.import_tasks: sites/karakeep.yml