---
- name: restart postfix
  ansible.builtin.systemd:
    name: postfix
    state: restarted

- name: postmap mailgun_passwd
  ansible.builtin.command: postmap /etc/postfix/sasl/mailgun_passwd
  notify: restart postfix

- name: restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: restart ssh
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: reconfigure eth0
  ansible.builtin.shell:
    cmd: |
      systemctl daemon-reload
      networkctl reload
      networkctl reconfigure -a eth0

- name: reconfigure eth1
  ansible.builtin.shell:
    cmd: |
      systemctl daemon-reload
      networkctl reload
      networkctl reconfigure -a eth1

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted