# Example dynamic configuration for Traefik
# Place this file in /etc/traefik/dynamic/ to add custom routes

http:
  routers:
    example-router:
      rule: "Host(`example.fzymgc.house`)"
      service: example-service
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      middlewares:
        - security-headers

  services:
    example-service:
      loadBalancer:
        servers:
          - url: "http://example-app:8080"

  middlewares:
    security-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
