---
- name: Ensure main-bridge network exists
  community.docker.docker_network:
    name: main-bridge
    state: present
    driver: bridge
    ipam_config:
      - subnet: "172.18.0.0/16"
        gateway: "172.18.0.1"
    driver_options:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: "{{ ansible_eth0.ipv4.address }}"
      com.docker.network.bridge.name: "main-bridge"
      com.docker.network.driver.mtu: "1500"
  notify: Restart cloudflared

- name: Ensure internal-bridge network exists
  community.docker.docker_network:
    name: internal-bridge
    state: present
    driver: bridge
    internal: true
    ipam_config:
      - subnet: "172.20.0.0/16"
        gateway: "172.20.0.1"
    driver_options:
      com.docker.network.bridge.enable_ip_masquerade: "false"
      com.docker.network.bridge.name: "internal-bridge"
  notify: Restart cloudflared

- name: Create Cloudflared Docker Compose File
  ansible.builtin.template:
    src: compose.yml.j2
    dest: "{{ cloudflared_config_directory }}/compose.yml"
    owner: "{{ cloudflared_user }}"
    group: "{{ cloudflared_group }}"
    mode: "{{ cloudflared_config_mode }}"
  notify: Restart cloudflared

- name: Create dockerignore file for Cloudflared
  ansible.builtin.copy:
    dest: "{{ cloudflared_config_directory }}/.dockerignore"
    content: |
      compose.yml
    owner: "{{ cloudflared_user }}"
    group: "{{ cloudflared_group }}"
    mode: "{{ cloudflared_config_mode }}"

- name: Create systemctl service for Cloudflared Docker Compose
  ansible.builtin.template:
    src: cloudflared-systemd.unit.j2
    dest: "/etc/systemd/system/cloudflared.service"
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd
    - Restart cloudflared

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Enable and start Cloudflared Docker service
  ansible.builtin.systemd:
    name: cloudflared
    enabled: yes
    state: started
