---
- ansible.builtin.debconf:
    name: postfix
    question: postfix/main_mailer_type
    value: "Satellite system"
    vtype: select

- ansible.builtin.debconf:
    name: postfix
    question: postfix/mailname
    value: "{{ ansible_fqdn }}"
    vtype: string

- ansible.builtin.debconf:
    name: postfix
    question: postfix/relayhost
    value: "[smtp.mailgun.org]:587"
    vtype: string

- name: Install packages for mail
  ansible.builtin.apt:
    name: "{{ common_packages_to_install_for_mail }}"
    state: latest
  tags:
    - packages

- ansible.builtin.meta: flush_handlers
- name: Add relay password
  ansible.builtin.copy:
    content: |
      [smtp.mailgun.org]:587 {{ mailgun_smtp_user }}:{{ mailgun_smtp_password }}
    dest: /etc/postfix/sasl/mailgun_passwd
    owner: root
    group: root
    mode: "0600"
  notify: Postmap mailgun_passwd

- name: Set etc mailname
  ansible.builtin.copy:
    dest: /etc/mailname
    owner: root
    group: root
    mode: "0644"
    content: "{{ ansible_fqdn }}"
  notify: Restart postfix

- name: Configure postfix
  ansible.builtin.template:
    src: postfix-main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: "0644"
  notify: Restart postfix
