- hosts: nas-support
  gather_facts: true
  become: true
  tags:
    - nas-support
  tasks:
    - name: Install fish
      ansible.builtin.package:
        name: fish
        state: present

    - name: Create user - sean
      ansible.builtin.user:
        name: sean
        shell: /usr/bin/fish
        groups: [adm, users, sudo, apps, fzymgc]
        append: true
    - name: Create sudoers.d file for users so they do not need a password
      ansible.builtin.copy:
        content: "sean ALL=(ALL) NOPASSWD:ALL"
        dest: /etc/sudoers.d/sean
        mode: "0440"
    - name: Add ssh key to admin user
      ansible.posix.authorized_key:
        user: sean
        state: present
        key: "{{ lookup('onepassword', 'ssh-key--seanb4t_ed25519', field='public key') }}"

  roles:
    - role: geerlingguy.docker
      docker_users: [fzymgc, sean]
      docker_install_compose_plugin: true
      docker_compose_package: docker-compose-plugin
      docker_compose_package_state: present
      tags: docker
    - role: artis3n.tailscale
      tailscale_authkey: "{{ lookup('community.general.onepassword', 'tailscale-oauth nas-app-proxy', field='password', vault='fzymgc-house') }}"
      tailscale_args: "--ssh --reset"
      tailscale_oauth_preauthorized: true
      tailscale_oauth_ephemeral: false
      tailscale_tags: [nas, shared]
      tags: tailscale
