---
# Install dnscrypt-proxy from the github releases page
- name: Stat dnscrypt-proxy to check if it is installed
  ansible.builtin.stat:
    path: "/usr/local/bin/dnscrypt-proxy-{{ dnscrypt_proxy_version }}"
  register: stat_result
  failed_when: false

- name: Download dnscrypt-proxy release
  ansible.builtin.get_url:
    url: "https://github.com/DNSCrypt/dnscrypt-proxy/releases/download/{{ dnscrypt_proxy_version }}/dnscrypt-proxy-linux_x86_64-{{ dnscrypt_proxy_version }}.tar.gz"
    dest: "/tmp/dnscrypt-proxy-linux_x86_64-{{ dnscrypt_proxy_version }}.tar.gz"
    mode: "0644"
  when: not stat_result.stat.exists
  register: download_result
  notify:
    - Restart dnscrypt-proxy

- name: Extract dnscrypt-proxy release
  ansible.builtin.unarchive:
    src: "/tmp/dnscrypt-proxy-linux_x86_64-{{ dnscrypt_proxy_version }}.tar.gz"
    dest: "/tmp"
    remote_src: true
  when: download_result is changed
  register: extract_result
  notify:
    - Restart dnscrypt-proxy

- name: Move dnscrypt-proxy binary to /usr/local/bin
  ansible.builtin.copy:
    src: "/tmp/linux-x86_64/dnscrypt-proxy"
    dest: "/usr/local/bin/dnscrypt-proxy-{{ dnscrypt_proxy_version }}"
    mode: "0755"
    remote_src: true
  when: extract_result is changed
  register: move_result
  notify:
    - Restart dnscrypt-proxy

- name: Create dnscrypt-proxy symlink
  ansible.builtin.file:
    src: "/usr/local/bin/dnscrypt-proxy-{{ dnscrypt_proxy_version }}"
    dest: "/usr/local/bin/dnscrypt-proxy"
    state: link
  when: move_result is changed
  register: symlink_result
  notify:
    - Restart dnscrypt-proxy

- name: Create dnscrypt-proxy service file
  ansible.builtin.copy:
    src: "dnscrypt-proxy.service"
    dest: "/etc/systemd/system/dnscrypt-proxy.service"
    mode: "0644"
  notify:
    - Reload systemd daemon
    - Restart dnscrypt-proxy

- name: Enable and start dnscrypt-proxy service
  ansible.builtin.systemd:
    name: dnscrypt-proxy
    state: started
    enabled: true

- name: Create dnscrypt-proxy configuration directory
  ansible.builtin.file:
    path: "/etc/dnscrypt-proxy"
    state: directory
    mode: "0755"

- name: Create dnscrypt-proxy configuration file
  ansible.builtin.template:
    src: "dnscrypt-proxy.toml.j2"
    dest: "/etc/dnscrypt-proxy/dnscrypt-proxy.toml"
    mode: "0644"
  notify:
    - Restart dnscrypt-proxy
